apiVersion: v1
kind: Pod
metadata:
  name: nginx-efs-dynamic-pod
  namespace: default
  labels:
    app: nginx-efs-dynamic
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: efs-storage
      mountPath: /usr/share/nginx/html
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "echo 'Hello from EFS Dynamic Volume! Pod: nginx-efs-dynamic-pod' > /usr/share/nginx/html/index.html"]
  volumes:
  - name: efs-storage
    persistentVolumeClaim:
      claimName: efs-dynamic-pvc