apiVersion: v1
kind: Pod
metadata:
  name: nginx-efs-static-pod
  namespace: default
  labels:
    app: nginx-efs-static
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: efs-storage
      mountPath: /usr/share/nginx/html
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    command: ["/bin/sh"]
    args: ["-c", "echo 'Hello from EFS Static Volume! Pod: '$POD_NAME > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"]
  volumes:
  - name: efs-storage
    persistentVolumeClaim:
      claimName: efs-static-pvc