apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-static-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-static-sc
  volumeName: efs-static-pv
  resources:
    requests:
      storage: 5Gi